### ISSUE TITLE
Could not download step by step guide

### ISSUE THREAD

**Issue by AndroidManikandan5689** [kyaroru/Karma#1]

**Comment by kyaroru** [comment]
hi do u able to view it?

**Comment by AndroidManikandan5689** [comment]
Hi,
I could not access. I got following response:

This site can’t be reached
drive.google.com’s server DNS address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN
-----Original Message-----

**Comment by kyaroru** [comment]
I think you can try this link :p https://1drv.ms/b/s!Ag6iLCenmbY6gZsmQCVu76sfBU3frw

**Comment by AndroidManikandan5689** [comment]
Great, Thank you very much

-----Original Message-----

**Comment by kyaroru** [comment]
Welcome :p
